name: Update_winds_como

# Controls when the workflow will run
on:
  schedule:
    # Minute(0-60), hour(0-23), day(1-31), month(1-12), day(Mon-Sun)
    # At 23:00 every days
    - cron: "00 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show CWD
        run: |
          pwd
          ls

      - name: Run code to DL files
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          retry_on: error
          timeout_seconds: 10
          command: |
            python src/main_colico.py

      - name: Commit DB
        run: |
          git config --global user.name 'Marc Automated Action'
          git config --global user.email 'Marc@users.noreply.github.com'
          git add db/*
          git commit -m "Automated Colico DB update"
          git push
