# This is a basic workflow to help you get started with Actions

name: Update_winds_CSV

# Controls when the workflow will run
on:
  schedule:
    # Minute(0-60), hour(0-23), day(1-31), month(1-12), day(Mon-Sun)
    # At minute 30 past every 3rd hour from 0 through 23.
    - cron: "30 0/3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Show CWD
        run: |
          pwd
          ls
      - name: Install dependencies
        run: pip install pandas beautifulsoup4
      - name: Run code to DL files
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 40
          command: |
            python src/main.py

      - name: Commit DB
        run: |
          git config --global user.name 'Marc Automated Action'
          git config --global user.email 'marc-moreaux@users.noreply.github.com'
          git add db/*
          git commit -m "Automated Silvaplana DB update"
          git push
